  spring:
    application:
      name:Lab1
    datasource:
      url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
      username: root
      password: P@ssword

  stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeout: 1000
    supported-currencies: USD,EUR,GBP
    payment-gateway: paypal